# Use Node.js base image
FROM node:18 as builder

# Set working directory
WORKDIR /app

# Copy only relevant files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/api ./apps/api
COPY packages ./packages

# Install dependencies
RUN npm install -g pnpm turbo RUN npm install -g pnpm turbo typescript next @nestjs/cli
RUN pnpm install --frozen-lockfile

# Build the NestJS app
RUN pnpm turbo run build --filter=...

# Use a smaller runtime image
FROM node:18-alpine

WORKDIR /app

# Copy the built app
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api/package.json ./package.json

# Expose the API port
EXPOSE 3005

# Command to run the app
CMD ["node", "dist/main"]
