

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: mydatabase
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/mydatabase
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306" # Expose MySQL on port 3307 externally
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Root password for the database
      MYSQL_DATABASE: mydatabase # Initialize the database
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data: # Named volume for database persistence
  

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true