version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    ports:
      - "4000:3005"
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages/shared:/app/packages/shared
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_HOST: mysql
      DATABASE_PORT: 3307
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: mydatabase
      DATABASE_URL: mysql://root:rootpassword@mysql:3307/mydatabase
    depends_on:
      - mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile.web.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages/shared:/app/packages/shared
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      API_URL: http://localhost:4000

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
