import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Package2Icon } from 'lucide-react';
import { Toaster } from '@/components/ui/toaster';
import TanstackProvider from '@/providers/tanstack';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex flex-col min-h-screen'>
          <header className='flex items-center h-16 px-4 border-b shrink-0 md:px-6'>
            <nav className='flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6'>
              <a
                className='flex items-center gap-2 text-lg font-semibold md:text-base'
                href='#'
              >
                <Package2Icon className='w-6 h-6' />
                <span className=''>AssetBook</span>
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/dashboard'>
                Dashboard
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/bookings'>
                Bookings
              </a>
              <a
                className='text-gray-500 dark:text-gray-400'
                href='/maintenance'
              >
                Maintenance
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/assets'>
                Assets
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/reports'>
                Reports
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/users'>
                Users
              </a>
              <a className='text-gray-500 dark:text-gray-400' href='/settings'>
                Settings
              </a>
            </nav>
          </header>
          <TanstackProvider>
          {children}
          </TanstackProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
